import { useParams } from 'react-router-dom';
import { useStore } from '../../store/StoreProvider';
import { useGo } from '../../hooks/useGo';
import { fmtDate, fmtDT, fmtQty } from '../../lib/format';
import { prod, loc, userName } from '../../lib/engine';
import { Diamond, Empty } from '../../components/ui';
import { Printer } from 'lucide-react';

export default function PrintView() {
  const { db } = useStore();
  const go = useGo();
  const { id } = useParams();
  const op = db.operations.find((o) => o.id === Number(id));
  const title = { RECEIPT: "GOODS RECEIPT NOTE", DELIVERY: "DELIVERY NOTE", INTERNAL: "INTERNAL TRANSFER", ADJUSTMENT: "STOCK ADJUSTMENT" };
  const back = () => (op ? go("opForm", { id: op.id }) : go("dashboard"));
  const units = op ? op.lines.reduce((a, l) => a + l.quantity, 0) : 0;
  const wh = op && db.warehouses.find((w) => w.id === op.warehouseId);
  return (
    <div style={{ minHeight: "100vh", padding: "24px 16px" }}>
      <div className="no-print flex items-center justify-between" style={{ maxWidth: 794, margin: "0 auto 16px" }}>
        <button type="button" className="btn bs" onClick={back}>← Back</button>
        {op?.status === "DONE" && <button type="button" className="btn bp" onClick={() => { try { window.print(); } catch (e) { /* noop */ } }}><Printer size={16} />Print</button>}
      </div>
      {!op || op.status !== "DONE" ? (
        <div className="card" style={{ maxWidth: 520, margin: "40px auto" }}><Empty icon={Printer} title="Printing is available after validation." sub="Validate the operation first, then print." /></div>
      ) : (
        <div className="doc" style={{ maxWidth: 794, margin: "0 auto", padding: 48, borderRadius: 4, boxShadow: "0 8px 32px rgba(0,0,0,.4)" }}>
          <div className="flex justify-between items-start">
            <div><div className="flex items-center gap-2" style={{ fontWeight: 600, fontSize: 18 }}><Diamond s={12} />StockSense</div>
              <div style={{ fontSize: 12, color: "#555", marginTop: 4 }}>{wh?.name}<br />{wh?.address}</div></div>
            <div style={{ textAlign: "right" }}><div style={{ fontSize: 12, letterSpacing: ".1em", color: "#555" }}>{title[op.type]}</div>
              <div className="mono" style={{ fontSize: 24, fontWeight: 600, marginTop: 4 }}>{op.reference}</div>
              <div style={{ display: "inline-block", marginTop: 6, border: "2px solid #1a9c57", color: "#1a9c57", padding: "2px 10px", borderRadius: 4, fontWeight: 700, fontSize: 12, letterSpacing: ".1em" }}>DONE</div></div>
          </div>
          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "8px 32px", margin: "28px 0", fontSize: 13 }}>
            {[["Contact", op.contact || "—"], [op.type === "DELIVERY" ? "Delivery Address" : "From", op.type === "DELIVERY" ? op.deliveryAddress : loc(db, op.sourceLocId).fullName],
              ["Schedule Date", fmtDate(op.scheduledDate)], ["To", loc(db, op.destLocId).fullName], ["Done Date", fmtDT(op.doneDate)], ["Responsible", userName(db, op.responsibleId)]]
              .map(([k, v]) => <div key={k}><div style={{ fontSize: 11, color: "#777", textTransform: "uppercase", letterSpacing: ".06em" }}>{k}</div><div>{v}</div></div>)}
          </div>
          <table><thead><tr><th>#</th><th>SKU</th><th>Product</th><th>UoM</th><th style={{ textAlign: "right" }}>Quantity</th></tr></thead>
            <tbody>{op.lines.map((l, i) => { const p = prod(db, l.productId); return (
              <tr key={i}><td>{i + 1}</td><td className="mono">{p?.sku}</td><td>{p?.name}</td><td>{p?.uom}</td><td className="mono" style={{ textAlign: "right" }}>{fmtQty(l.quantity)}</td></tr>); })}</tbody></table>
          <div style={{ textAlign: "right", fontSize: 13, marginTop: 12 }}>Total: {op.lines.length} products · {fmtQty(units)} units</div>
          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 48, marginTop: 64, fontSize: 12, color: "#555" }}>
            <div style={{ borderTop: "1px solid #999", paddingTop: 6 }}>Delivered by</div>
            <div style={{ borderTop: "1px solid #999", paddingTop: 6 }}>Received by</div>
          </div>
          <div style={{ fontSize: 11, color: "#999", marginTop: 40, textAlign: "center" }}>Generated by StockSense · {fmtDT(Date.now())} · Page 1 of 1</div>
        </div>)}
    </div>
  );
}
